

export function feature_descriptions(feature:string){

const feature_descr = {theobolus:"Theophylline bolus mg",
norbolus:"Noradrenaline bolus µg",
iloprost:"Iloprost µg",
adrebolus:"Adrenaline bolus µg",
theoperf:"Theophylline infusion mg/h",
nipruss:"Nipruss mg/h",
abpd:"Diastolic Blood Pressure",
abps:"Systolic BP",
abpm:"Mean BP",
PAPs:"Pulmonary arterial Pressure systolic",
PAPd:"PAP diastolic",
PAPm:"PAP mean",
HR:"Heart rate",
ZVDm:"Central venous pressure, mean",
CO:"Cardiac Output, L/min",
SvO2:"Venous Oxygen Saturation, %",
PEEP:"Positive End-Expiratory Pressure, cmH2O",
ESV:"End-Systolic Volume of blood in the heart, ml",
RVEF:"Right Ventricular Ejection Fraction, %",
SVI:"Stroke Volume Index, ml/beat/m2",
ESVI:"End-Systolic Volume Index",
CI:"Cardiac Index, L/min/m2",
DO2:"Oxygen delivery, ml/min",
O2_Index:"Oxygenation index",
PVR:"Pulmonary vascular resistance",
PVRi:"Pulmonary vascular resistance index",
SV:"Stroke Volume, ml",
SVR:"Systemic Vascular Resistance",
SVRi:"Systemic Vascular Resistance Index",
hourly_urin_ml:"(actual) hourly_urin_ml",
theostart:"Theophyllin start date & time",
timesincetheo:"Time since Theophyllin start, min",
urine_bl:" urine output at baseline, ml/h (mean of the 6 hours before Theophyllin start",
urine_6hrs:"Urine output at 6 hours, ml/h",
urine_12hrs:"UO at 12 h",
urine_18hrs:"UO at 18h",
urine_24hrs:"UO at24h",
Urea_bl:"Urea level at baseline, mg/l",
Urea_6hrs:"Urea at 6h",
Urea_12hrs:"Urea at 12h",
Urea_18hrs:"Urea at 18h",
Urea_24hrs:"Urea at 24h",
Crea_bl:"Creaninine level at baseline",
Crea_6hrs:"(mean) Crea_6hrs",
Crea_12hrs:"(mean) Crea_12hrs",
Crea_18hrs:"(mean) Crea_18hrs",
Crea_24hrs:"(mean) Crea_24hrs",
Lac_bl:"Lactate level at baseline",
Lac_6hrs:"(mean) Lac_6hrs",
Lac_12hrs:"(mean) Lac_12hrs",
Lac_18hrs:"(mean) Lac_18hrs",
Lac_24hrs:"(mean) Lac_24hrs",
Na_bl:"Natrium (sodium) at baseline",
Na_6hrs:"(mean) Na_6hrs",
Na_12hrs:"(mean) Na_12hrs",
Na_18hrs:"(mean) Na_18hrs",
Na_24hrs:"(mean) Na_24hrs",
Temp_bl:"Temperature at baseline",
Temp_6hrs:"(mean) Temp_6hrs",
Temp_12hrs:"(mean) Temp_12hrs",
Temp_18hrs:"(mean) Temp_18hrs",
Temp_24hrs:"(mean) Temp_24hrs",
pH_bl:"Blood pH at baseline",
pH_6hrs:"(mean) pH_6hrs",
pH_12hrs:"(mean) pH_12hrs",
pH_18hrs:"(mean) pH_18hrs",
pH_24hrs:"(mean) pH_24hrs",
PP:"Pulse Pressure = Systolic - Diastolic BP",
perfpress:"Perfusion Pressure = Mean BP - CVP",
COresponder:"1 = Responder (increased the CO by >10% after Theophylline); 0 = Non-Responder",
T_resp:"(mean) T_resp",
drop:"1 = patient had no baseline CO measurement",

admsource_n:"admissionsource",
age:"Age",
apache2:"APACHE II score",
bmi:"Body mass index",
bsa_n:"BSA",

extubation_date:"Extubation date&time",
honvaso:"Hours on vasopressors",
height_n:"Height",

icu_days:"Days in ICU (ICU lenght of stay)",

icuoutcome_n:"ICU outcome (dead or alive)",
ihd:"Intermittent Hemodyalisis",
intubationtime:"Intubation date&time",
patientsex_n:"Gender",
r_apache:"APACHE risk of death",
rrt:"Renal replacement therapy",
rrt_start:"RRT start date&time",
saps:"Simplified Acute Physiology Score (SAPS)",

tracheostoma:"tracheostomy date",
weight_n:"Weight",
Cancer:"    cancer",
Dialysis:"was on dialysis before ICU",
trach:"had a tracheostomy",
idtag:"1 = first row in every patient ",
dobutamine:"Dobutamine µg/min",
adrenaline:"Adrenaline µg/min",
noradrenaline:"Noradrenaline µg/min",
nitroprussid:"Nitroprusside µg/min",
theoboli:"Number of Theophylline boli per patient",
theoinf:"1= Received a Theophylline infusion (not only a bolus)",
theodose:"Cumulative Theophylline dose per patient",
mvent:"Mechanical ventilation",
blmv:"Mech. ventilation at baseline",
everdobu:"ever received dobutamine",
bldobu:"Dobutamine at baseline yn",
everadre:"ever received Adrenaline",
bladre:"Adrenaline at baseline yn",
evernor:"ever received Noradrenline",
blnor:"Noradrenaline at baseline yn",
evernipruss:"ever received Nipruss",
blnipruss:"Nipruss at baseline yn",
everlevo:"ever received Levosimendan",
blevo:"Levo at baseline yn",
everilo:"ever received Iloprost",
blilo:"Iloprost at baseline yn",
neq_kg_min:"Noradrenaline equivalents (sum of adrenaline and noradrenaline), µg/kg/min",
levo_kgmin:"Levosimendan µg/kg/min",
abpd_bl:"Baseline abpd",
abpd_dbl:"abpd absolute difference from baseline",
abpd_rdbl:"abpd relative change from baseline in %",
abpd_dblmax:"abpd maximal change from baseline",
abpd_dblmin:"abpd minimal change from baseline",
abps_bl:"Baseline abps",
abps_dbl:"abps absolute difference from baseline",
abps_rdbl:"abps relative change from baseline in %",
abps_dblmax:"abps maximal change from baseline",
abps_dblmin:"abps minimal change from baseline",
abpm_bl:"Baseline abpm",
abpm_dbl:"abpm absolute difference from baseline",
abpm_rdbl:"abpm relative change from baseline in %",
abpm_dblmax:"abpm maximal change from baseline",
abpm_dblmin:"abpm minimal change from baseline",
PAPs_bl:"Baseline PAPs",
PAPs_dbl:"PAPs absolute difference from baseline",
PAPs_rdbl:"PAPs relative change from baseline in %",
PAPs_dblmax:"PAPs maximal change from baseline",
PAPs_dblmin:"PAPs minimal change from baseline",
PAPd_bl:"Baseline PAPd",
PAPd_dbl:"PAPd absolute difference from baseline",
PAPd_rdbl:"PAPd relative change from baseline in %",
PAPd_dblmax:"PAPd maximal change from baseline",
PAPd_dblmin:"PAPd minimal change from baseline",
PAPm_bl:"Baseline PAPm",
PAPm_dbl:"PAPm absolute difference from baseline",
PAPm_rdbl:"PAPm relative change from baseline in %",
PAPm_dblmax:"PAPm maximal change from baseline",
PAPm_dblmin:"PAPm minimal change from baseline",
HR_bl:"Baseline HR",
HR_dbl:"HR absolute difference from baseline",
HR_rdbl:"HR relative change from baseline in %",
HR_dblmax:"HR maximal change from baseline",
HR_dblmin:"HR minimal change from baseline",
ZVDm_bl:"Baseline ZVDm",
ZVDm_dbl:"ZVDm absolute difference from baseline",
ZVDm_rdbl:"ZVDm relative change from baseline in %",
ZVDm_dblmax:"ZVDm maximal change from baseline",
ZVDm_dblmin:"ZVDm minimal change from baseline",
CO_bl:"Baseline CO",
CO_dbl:"CO absolute difference from baseline",
CO_rdbl:"CO relative change from baseline in %",
CO_dblmax:"CO maximal change from baseline",
CO_dblmin:"CO minimal change from baseline",
SvO2_bl:"Baseline SvO2",
SvO2_dbl:"SvO2 absolute difference from baseline",
SvO2_rdbl:"SvO2 relative change from baseline in %",
SvO2_dblmax:"SvO2 maximal change from baseline",
SvO2_dblmin:"SvO2 minimal change from baseline",
PEEP_bl:"Baseline PEEP",
PEEP_dbl:"PEEP absolute difference from baseline",
PEEP_rdbl:"PEEP relative change from baseline in %",
PEEP_dblmax:"PEEP maximal change from baseline",
PEEP_dblmin:"PEEP minimal change from baseline",
ESV_bl:"Baseline ESV",
ESV_dbl:"ESV absolute difference from baseline",
ESV_rdbl:"ESV relative change from baseline in %",
ESV_dblmax:"ESV maximal change from baseline",
ESV_dblmin:"ESV minimal change from baseline",
RVEF_bl:"Baseline RVEF",
RVEF_dbl:"RVEF absolute difference from baseline",
RVEF_rdbl:"RVEF relative change from baseline in %",
RVEF_dblmax:"RVEF maximal change from baseline",
RVEF_dblmin:"RVEF minimal change from baseline",
SVI_bl:"Baseline SVI",
SVI_dbl:"SVI absolute difference from baseline",
SVI_rdbl:"SVI relative change from baseline in %",
SVI_dblmax:"SVI maximal change from baseline",
SVI_dblmin:"SVI minimal change from baseline",
ESVI_bl:"Baseline ESVI",
ESVI_dbl:"ESVI absolute difference from baseline",
ESVI_rdbl:"ESVI relative change from baseline in %",
ESVI_dblmax:"ESVI maximal change from baseline",
ESVI_dblmin:"ESVI minimal change from baseline",
CI_bl:"Baseline CI",
CI_dbl:"CI absolute difference from baseline",
CI_rdbl:"CI relative change from baseline in %",
CI_dblmax:"CI maximal change from baseline",
CI_dblmin:"CI minimal change from baseline",
DO2_bl:"Baseline DO2",
DO2_dbl:"DO2 absolute difference from baseline",
DO2_rdbl:"DO2 relative change from baseline in %",
DO2_dblmax:"DO2 maximal change from baseline",
DO2_dblmin:"DO2 minimal change from baseline",
O2_Index_bl:"Baseline O2_Index",
O2_Index_dbl:"O2_Index absolute difference from baseline",
O2_Index_rdbl:"O2_Index relative change from baseline in %",
O2_Index_dblmax:"O2_Index maximal change from baseline",
O2_Index_dblmin:"O2_Index minimal change from baseline",
PVR_bl:"Baseline PVR",
PVR_dbl:"PVR absolute difference from baseline",
PVR_rdbl:"PVR relative change from baseline in %",
PVR_dblmax:"PVR maximal change from baseline",
PVR_dblmin:"PVR minimal change from baseline",
PVRi_bl:"Baseline PVRi",
PVRi_dbl:"PVRi absolute difference from baseline",
PVRi_rdbl:"PVRi relative change from baseline in %",
PVRi_dblmax:"PVRi maximal change from baseline",
PVRi_dblmin:"PVRi minimal change from baseline",
SV_bl:"Baseline SV",
SV_dbl:"SV absolute difference from baseline",
SV_rdbl:"SV relative change from baseline in %",
SV_dblmax:"SV maximal change from baseline",
SV_dblmin:"SV minimal change from baseline",
SVR_bl:"Baseline SVR",
SVR_dbl:"SVR absolute difference from baseline",
SVR_rdbl:"SVR relative change from baseline in %",
SVR_dblmax:"SVR maximal change from baseline",
SVR_dblmin:"SVR minimal change from baseline",
SVRi_bl:"Baseline SVRi",
SVRi_dbl:"SVRi absolute difference from baseline",
SVRi_rdbl:"SVRi relative change from baseline in %",
SVRi_dblmax:"SVRi maximal change from baseline",
SVRi_dblmin:"SVRi minimal change from baseline",
PP_bl:"Baseline PP",
PP_dbl:"PP absolute difference from baseline",
PP_rdbl:"PP relative change from baseline in %",
PP_dblmax:"PP maximal change from baseline",
PP_dblmin:"PP minimal change from baseline",
perfpress_bl:"Baseline perfpress",
perfpress_dbl:"perfpress absolute difference from baseline",
perfpress_rdbl:"perfpress relative change from baseline in %",
survivor:"1=Survivor 0= Non-survivor"}


if (feature in feature_descr){
    
    return "Description: " + feature_descr[feature as keyof typeof feature_descr];
}
else {
    return 
}

}

